-- PostgreSQL setup script
-- Part of this database script is auto-generated by WebStorm Database Tool
-- WARNING: This script will drop all exist tables. Use only at server setup!

-- drop everything
-- TABLE
DROP TABLE IF EXISTS "public"."city";
DROP TABLE IF EXISTS "public"."group";
DROP TABLE IF EXISTS "public"."users";
-- SEQUENCE
DROP SEQUENCE IF EXISTS "public".t_city_city_id_seq;
DROP SEQUENCE IF EXISTS "public".t_group_group_id_seq;
DROP SEQUENCE IF EXISTS "public"."user_user_id_seq";

-- Sequences used by table
-- Contains: city id, group id, user id
-- TODO: add post id, etc.
CREATE SEQUENCE "public".t_city_city_id_seq
    INCREMENT 1
    MINVALUE  1
    MAXVALUE 2147483647
    START 1
    CACHE 1;
CREATE SEQUENCE "public".t_group_group_id_seq
    INCREMENT 1
    MINVALUE  1
    MAXVALUE 2147483647
    START 1
    CACHE 1;
CREATE SEQUENCE "public"."users_user_id_seq"
    INCREMENT 1
    MINVALUE  1
    MAXVALUE 2147483647
    START 1
    CACHE 1;

-- Tables
-- Contains: city, group, user
-- TODO: add post, favourite

CREATE TABLE "public"."city" (
    "city_id" int4 NOT NULL DEFAULT nextval('t_city_city_id_seq'::regclass),
    "city_name" char(100) COLLATE "pg_catalog"."default" NOT NULL
);
-- In current version we only have these three cities running
INSERT INTO "public"."city" VALUES (0, 'San Francisco');
INSERT INTO "public"."city" VALUES (1, 'Los Angeles');
INSERT INTO "public"."city" VALUES (2, 'San Jose');

-- In current version we have 3 user groups
CREATE TABLE "public"."group" (
    "group_id" int4 NOT NULL DEFAULT nextval('t_group_group_id_seq'::regclass),
    "group_name" char(100) COLLATE "pg_catalog"."default" NOT NULL
);
INSERT INTO "public"."group" VALUES (0, 'Admin');
INSERT INTO "public"."group" VALUES (1, 'Verified User');
INSERT INTO "public"."group" VALUES (2, 'User');

CREATE TABLE "public"."users" (
    "user_id" int4 NOT NULL DEFAULT nextval('users_user_id_seq'::regclass),
    "email" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
    "pwd" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
    "name" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
    "city_id" int4 NOT NULL,
    "group_id" int4 NOT NULL,
    "createdAt" date,
    "updatedAt" date
);

-- Owned by relationship
ALTER SEQUENCE "public"."t_city_city_id_seq" OWNED BY "public"."city"."city_id";
ALTER SEQUENCE "public"."t_group_group_id_seq" OWNED BY "public"."group"."group_id";
ALTER SEQUENCE "public"."users_user_id_seq" OWNED BY "public"."users"."user_id";

-- Primary key
ALTER TABLE "public"."city" ADD CONSTRAINT "t_city_pkey" PRIMARY KEY ("city_id");
ALTER TABLE "public"."group" ADD CONSTRAINT "t_group_pkey" PRIMARY KEY ("group_id");
ALTER TABLE "public"."users" ADD CONSTRAINT user_pkey PRIMARY KEY ("user_id");

-- Grant public access
GRANT USAGE ON SCHEMA public TO "muzhizhang";